apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o6j7n1e9y-nodejs 
  janus-idp.io/tekton: o6j7n1e9y-nodejs
  backstage.io/kubernetes-id: o6j7n1e9y-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o6j7n1e9y-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml