apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: o6j7n1e9y-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o6j7n1e9y-nodejs 
  name: o6j7n1e9y-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: o6j7n1e9y-nodejs
    weight: 100 
