apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o6j7n1e9y-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o6j7n1e9y-nodejs 
  name: o6j7n1e9y-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: o6j7n1e9y-nodejs 
